### PR TITLE
Pass through the directories

### PR DESCRIPTION
**Pull request by shinnn**
Related discussion: https://github.com/jgable/gulp-cache/pull/41#issuecomment-75592549

### CODE REVIEW

**Comment by jgable** [comment]
:+1:

**Comment by shinnn** [comment]
By the way, how do you think about coding styles? You switched the style to two spaces in cache-swap project (https://github.com/jgable/cache-swap/commit/2fe69034abd06f66694768c30bc20c402db2b5e1). I'd like to use two-space style in this project too.

**Comment by jgable** [comment]
I'm ok with 2 spaces, just haven't spent the time switching over.  My last company had a 4 space rule so my editor was set up for that by default.  Facebook does 2 spaces and that's what I have now.

If you want to add a .editorconfig I'm down with that.

**Comment by shinnn** [comment]
Thanks. I'll add .editorconfig file.

**Pull request merged**
